#!/bin/bash
set -e

# Check for required arguments
if [ "$#" -ne 3 ]; then
    echo "Usage: $0 RC_BRANCH IOS_AFSDK ANDROID_AFSDK"
    exit 1
fi

RC_BRANCH=$1
IOS_AFSDK=$2
ANDROID_AFSDK=$3

# Extract the version from RC_BRANCH.
# Expected RC_BRANCH format: releases/[...]/[...]/<version>_rc<number>
if [[ $RC_BRANCH =~ .*/([0-9]+\.[0-9]+\.[0-9]+)_rc[0-9]+$ ]]; then
    NEW_VERSION="${BASH_REMATCH[1]}"
else
    echo "Error: RC_BRANCH does not match expected format."
    exit 1
fi

echo "New version: $NEW_VERSION"
echo "iOS AFSDK: $IOS_AFSDK"
echo "Android AFSDK: $ANDROID_AFSDK"

# 1. Update pubspec.yml: Change version: line to the new version.
sed -i.bak -E "s/(version: )[0-9]+\.[0-9]+\.[0-9]+/\1$NEW_VERSION/" pubspec.yaml

# 2. Update ios/Classes/AppsflyerSdkPlugin.h: Change kAppsFlyerPluginVersion to the new version.
sed -i.bak -E "s/(#define[[:space:]]+kAppsFlyerPluginVersion[[:space:]]+@\")([0-9]+\.[0-9]+\.[0-9]+)(\")/\1$NEW_VERSION\3/" ios/Classes/AppsflyerSdkPlugin.h

# 3. Update ios/appsflyer_sdk.podspec:
#    a. Update s.version
sed -i.bak -E "s/(  s.version          = ')[0-9]+\.[0-9]+\.[0-9]+(')/\1$NEW_VERSION\2/" ios/appsflyer_sdk.podspec
#    b. Update the dependency for AppsFlyerFramework to use IOS_AFSDK.
sed -i.bak -E "s/(  s.ios.dependency 'AppsFlyerFramework',')[0-9]+\.[0-9]+\.[0-9]+(')/\1$IOS_AFSDK\2/" ios/appsflyer_sdk.podspec

# 4. Update CHANGELOG.md: Insert a new empty section for the new version.
#    Find the first occurrence of "# Versions" and insert the new version header right after it.
line=$(grep -n "# Versions" CHANGELOG.md | head -n 1 | cut -d: -f1)
if [ -z "$line" ]; then
  echo "Error: '# Versions' not found in CHANGELOG.md"
  exit 1
fi

sed -i.bak "${line}a\\
\\
## $NEW_VERSION\\
\\
" CHANGELOG.md

# 5. Update android/src/main/java/com/appsflyer/appsflyersdk/AppsFlyerConstants.java:
#    Change PLUGIN_VERSION to the new version.
sed -i.bak -E "s/(final static String PLUGIN_VERSION[[:space:]]*=[[:space:]]*\")[0-9]+\.[0-9]+\.[0-9]+(\")/\1$NEW_VERSION\2/" android/src/main/java/com/appsflyer/appsflyersdk/AppsFlyerConstants.java

# 6. Update android/build.gradle: Change the dependency version for af-android-sdk to use ANDROID_AFSDK.
sed -i.bak -E "s/(implementation 'com\.appsflyer:af-android-sdk:)[0-9]+\.[0-9]+\.[0-9]+(')/\1$ANDROID_AFSDK\2/" android/build.gradle

echo "SDK bump complete."

# Optionally, remove backup files generated by sed.
find . -name "*.bak" -type f -delete

