name: Build Android

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd example
          flutter pub get

      - name: Build APK
        run: |
          cd example
          flutter build apk