name: Build iOS

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CocoaPods
        run: |
          cd example
          flutter pub get
          cd ios
          sudo gem install cocoapods

      - name: Install Pods
        run: |
          cd example/ios
          pod install --repo-update

      - name: Build iOS app
        run: |
          cd example
          flutter build ios --release --no-codesign